// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fiemjdjwmrrhnhvagtbn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZpZW1qZGp3bXJyaG5odmFndGJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5MjEyNzksImV4cCI6MjA1OTQ5NzI3OX0.qDLBizON3LMy2MlYFRifMl-y-dGMczaRi4g1VM3C7d0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);